### ISSUE TITLE
100% CPU usage after OAuth/app stalls

### ISSUE THREAD

**Issue by mcataford** [apancik/plain-email#1]
The app stalls after OAuth exchange, response is never received despite successful pass of the Google Auth popup. App status stays at "SHOWING AUTH".

Also of note: CPU goes to 100% on NodeJS process.

Env.: Windows 10 x64, Node v7.4.0, `npm install` is successful without significant warns.

**Comment by jrk** [comment]
Different env and slightly different observed behavior, but I had to upgrade the `googleapis` package to get passed auth.
